# Generated by Django 4.2.2 on 2023-09-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks", old_name="desc", new_name="taskdesc",
        ),
        migrations.RenameField(
            model_name="tasks", old_name="taskTitle", new_name="tasktitle",
        ),
    ]
